name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  email_validator: ^2.0.1
  awesome_snackbar_content: ^0.1.3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  carousel_slider: ^3.0.0
  get: ^4.3.8
  cloud_firestore: ^4.7.1
  firebase_core: ^2.13.0
  fluttertoast: ^8.2.2
  flutter_paypal_checkout: ^1.0.1
  http: ^0.13.4
  image_picker: ^1.0.0
  http_parser: ^4.0.0
  shared_preferences: ^2.2.0
  stroke_text: ^0.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
flutter_icons:
  android: true
  ios: true
  image_path: "assets/LogoApp.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/web_hi_res_512.png"
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/nguyen.png
    - assets/page-1/images/shopping-cart.png
    - assets/page-1/images/icon-arrow-left.png
    - assets/page-1/images/icon-square-arrow-up.png
    - assets/page-1/images/icon-arrow-left-qw6.png
    - assets/page-1/images/auto-group-dldv.png
    - assets/page-1/images/icon-person.png
    - assets/page-1/images/icon-arrow-left-RB6.png
    - assets/page-1/images/icon-eye-off.png
    - assets/page-1/images/icon-bell.png
    - assets/page-1/images/icon-house.png
    - assets/page-1/images/edit-image.png
    - assets/page-1/images/icon-arrow-left-bvQ.png
    - assets/page-1/images/icon-arrow-left-9TN.png
    - assets/page-1/images/icon-calendar.png
    - assets/page-1/images/mask-group.png
    - assets/page-1/images/auto-group-wvbw.png
    - assets/page-1/images/icon-arrow-left-RQt.png
    - assets/page-1/images/icon-bookmark.png
    - assets/page-1/images/icon-cube-box-fill.png
    - assets/page-1/images/auto-group-czrq.png
    - assets/page-1/images/icon-arrow-left-rsA.png
    - assets/page-1/images/icon-search.png
    - assets/page-1/images/icon-house-CUG.png
    - assets/page-1/images/profile.png
    - assets/page-1/images/vector.png
    - assets/page-1/images/icon-hourglass.png
    - assets/page-1/images/icon-arrow-left-9Gc.png
    - assets/page-1/images/icon-arrow-left-EHn.png
    - assets/page-1/images/icon-eye-off-ybN.png
    - assets/page-1/images/edit-image-hk4.png
    - assets/page-1/images/icon-arrow-left-2un.png
    - assets/page-1/images/icon-eye-off-weQ.png
    - assets/page-1/images/icon-arrow-left-TiY.png
    - assets/page-1/images/frame-246.png
    - assets/page-1/images/auto-group-occg.png
    - assets/page-1/images/icon-chevron-down.png
    - assets/page-1/images/logo-01-1.png
    - assets/page-1/images/icon-arrow-left-Vqr.png
    - assets/page-1/images/auto-group-3whe.png
    - assets/page-1/images/google.png
    - assets/page-1/images/icon-lock-shield.png
    - assets/page-1/images/icon-bookmark-fill.png
    - assets/page-1/images/auto-group-zojg.png
    - assets/page-1/images/icon-person-crop-circle.png
    - assets/page-1/images/icon-checkmark-square-fill.png
    - assets/page-1/images/icon-checkmark-square-fill-v8p.png
    - assets/page-1/images/mask-group-EvC.png
    - assets/page-1/images/icon-bookmark-4PS.png
    - assets/page-1/images/vector-Fip.png
    - assets/page-1/images/logo-01-2.png
    - assets/page-1/images/auto-group-xwtn.png
    - assets/page-1/images/mask-group-1E8.png
    - assets/page-1/images/icon-eye-off-xwz.png
    - assets/page-1/images/icon-checkmark-square-fill-JmN.png
    - assets/page-1/images/vector-is2.png
    - assets/page-1/images/auto-group-l4yp.png
    - assets/page-1/images/vector-fzp.png
    - assets/page-1/images/auto-group-svds.png
    - assets/page-1/images/icon-eye-off-Pvp.png
    - assets/page-1/images/rectangle-18.png
    - assets/page-1/images/icon-chevron-down-tAk.png
    - assets/page-1/images/icon-compass.png
    - assets/page-1/images/icon-eye-off-kik.png
    - assets/page-1/images/mask-group-JkG.png
    - assets/page-1/images/vector-8kY.png
    - assets/page-1/images/loading.png
    - assets/page-1/images/auto-group-huti.png
    - assets/page-1/images/vector-Azc.png
    - assets/page-1/images/icon-bookmark-Hg4.png
    - assets/page-1/images/icon-arrow-left-F76.png
    - assets/page-1/images/vector-uHA.png
    - assets/page-1/images/icon-arrow-left-cBa.png
    - assets/page-1/images/auto-group-dc7r.png
    - assets/page-1/images/mask-group-Zxt.png
    - assets/page-1/images/mask-group-X5a.png
    - assets/page-1/images/frame-249.png
    - assets/page-1/images/icon-settings.png
    - assets/page-1/images/icon-person-crop-circle-fill.png
    - assets/page-1/images/icon-bookmark-Fon.png
    - assets/page-1/images/icon-arrow-left-Puz.png
    - assets/page-1/images/vector-wxk.png
    - assets/page-1/images/mask-group-LTi.png
    - assets/page-1/images/vector-Kix.png
    - assets/page-1/images/left-arrow.png
    - assets/page-1/images/icon-house-ecG.png
    - assets/page-1/images/mask-group-Fcc.png
    - assets/page-1/images/icon-bookmark-QBz.png
    - assets/page-1/images/jimmy-fermin-bqe0j0b26rq-unsplash-2.png
    - assets/page-1/images/icon-bookmark-Bjn.png
    - assets/page-1/images/mask-group-j2p.png
    - assets/page-1/images/mask-group-BAY.png
    - assets/page-1/images/magnifiying-glass.png
    - assets/page-1/images/mask-group-UA4.png
    - assets/page-1/images/icon-eye-off-Ufa.png
    - assets/page-1/images/mask-group-75A.png
    - assets/page-1/images/magnifiying-glass-Yg8.png
    - assets/page-1/images/mask-group-bnp.png
    - assets/page-1/images/icon-options-horizontal.png
    - assets/page-1/images/icon-options-horizontal-jYt.png
    - assets/page-1/images/magnifiying-glass-GWC.png
    - assets/page-1/images/icon-eye-off-7cc.png
    - assets/page-1/images/icon-eye-off-7W8.png
    - assets/page-1/images/icon-options-horizontal-kSc.png
    - assets/page-1/images/icon-options-horizontal-Rag.png
    - assets/page-1/images/icon-options-horizontal-koJ.png
    - assets/page-1/images/mask-group-gFa.png
    - assets/page-1/images/group-263.png
    - assets/page-1/images/icon-checkmark-alt.png
    - assets/page-1/images/icon-settings-YBz.png
    - assets/page-1/images/left-arrow-Qsz.png
    - assets/page-1/images/mask-group-jn8.png
    - assets/page-1/images/icon-eye-off-o9i.png
    - assets/page-1/images/icon-arrow-left-Mbn.png
    - assets/page-1/images/mask-group-GKz.png
    - assets/page-1/images/icon-bookmark-Tgc.png
    - assets/page-1/images/icon-arrow-left-vwS.png
    - assets/page-1/images/mask-group-Hex.png
    - assets/page-1/images/icon-checkmark-square-fill-T2G.png
    - assets/page-1/images/mask-group-fBW.png
    - assets/page-1/images/mask-group-zaC.png
    - assets/page-1/images/mask-group-Ggx.png
    - assets/page-1/images/icon-xmark.png
    - assets/page-1/images/icon-xmark-X1S.png
    - assets/page-1/images/group-263-vyv.png
    - assets/page-1/images/mask-group-HWG.png
    - assets/page-1/images/icon-arrow-right-arrow-left.png
    - assets/page-1/images/mask-group-sVi.png
    - assets/page-1/images/group-238.png
    - assets/page-1/images/group-263-pxQ.png
    - assets/page-1/images/group-237.png
    - assets/page-1/images/auto-group-ebfw.png
    - assets/page-1/images/icon-checkmark-square-fill-6uv.png
    - assets/page-1/images/mask-group-TkU.png
    - assets/page-1/images/icon-xmark-FoN.png
    - assets/page-1/images/icon-xmark-2Br.png
    - assets/page-1/images/icon-search-NmW.png
    - assets/page-1/images/vector-jMA.png
    - assets/page-1/images/mask-group-vc8.png
    - assets/page-1/images/icon-suit-heart.png
    - assets/page-1/images/mask-group-uuz.png
    - assets/page-1/images/icon-xmark-LHN.png
    - assets/page-1/images/icon-xmark-3hS.png
    - assets/page-1/images/mask-group-Rzp.png
    - assets/page-1/images/icon-xmark-uf6.png
    - assets/page-1/images/group-263-Eik.png
    - assets/page-1/images/mask-group-ywE.png
    - assets/page-1/images/mask-group-wdA.png
    - assets/page-1/images/mask-group-Ez4.png
    - assets/page-1/images/michael-dam-mez3pofgsk-unsplash-2.png
    - assets/page-1/images/mask-group-HiQ.png
    - assets/page-1/images/mask-group-dXN.png
    - assets/page-1/images/mask-group-YMv.png
    - assets/page-1/images/mask-group-AtG.png
    - assets/page-1/images/icon-arrow-left-eGx.png
    - assets/page-1/images/icon-xmark-Wa4.png
    - assets/page-1/images/mask-group-LqN.png
    - assets/page-1/images/mask-group-nfS.png
    - assets/page-1/images/mask-group-iTJ.png
    - assets/page-1/images/mask-group-yi8.png
    - assets/page-1/images/icon-timer.png
    - assets/page-1/images/vector-5Jp.png
    - assets/page-1/images/mask-group-icY.png
    - assets/page-1/images/icon-bookmark-AV6.png
    - assets/page-1/images/mask-group-tPi.png
    - assets/page-1/images/mask-group-MHr.png
    - assets/page-1/images/icon-arrow-left-vCg.png
    - assets/page-1/images/icon-suit-heart-fill.png
    - assets/page-1/images/auto-group-5dg4.png
    - assets/page-1/images/icon-heart-circle.png
    - assets/page-1/images/auto-group-mxui.png
    - assets/page-1/images/auto-group-8cel.png
    - assets/page-1/images/auto-group-pdxw.png
    - assets/page-1/images/wevanfewoffoodgradientsaroundblackfloorhavespaceinthb862f807-891a-4b16-83a5-6a5be325efec100321-1-bg.png
    - assets/page-1/images/xa-lach-1.png
    - assets/page-1/images/heart-tJt.png
    - assets/page-1/images/heart-5Te.png
    - assets/page-1/images/icon-arrow-left-KGt.png
    - assets/page-1/images/rectangle-37-bg.png
    - assets/page-1/images/icon-search-qxU.png
    - assets/page-1/images/auto-group-afn8.png
    - assets/page-1/images/icon-suit-heart-fill-dCt.png
    - assets/page-1/images/icon-arrow-left-4wi.png
    - assets/page-1/images/mask-group-XmJ.png
    - assets/page-1/images/icon-location.png
    - assets/page-1/images/heart-45n.png
    - assets/page-1/images/icon-suit-heart-hrx.png
    - assets/page-1/images/mask-group-MgU.png
    - assets/page-1/images/auto-group-eeqg.png
    - assets/page-1/images/heart-3oE.png
    - assets/page-1/images/mask-group-jyA.png
    - assets/page-1/images/icon-eye-off-ELG.png
    - assets/page-1/images/google-eZe.png
    - assets/page-1/images/facebook.png
    - assets/page-1/images/icon-square-pencil.png
    - assets/page-1/images/vector-q9A.png
    - assets/page-1/images/edit-image-qhr.png
    - assets/page-1/images/icon-arrow-left-YgG.png
    - assets/page-1/images/icon-chevron-down-TCC.png
    - assets/page-1/images/logout.png
    - assets/page-1/images/vector-VY4.png
    - assets/page-1/images/icon-person-crop-circle-UhE.png
    - assets/page-1/images/vector-n1e.png
    - assets/page-1/images/vector-fqA.png
    - assets/page-1/images/logout-8mn.png
    - assets/page-1/images/icon-person-crop-circle-4CG.png
    - assets/page-1/images/icon-bell-circle-fill.png
    - assets/page-1/images/vector-Kuz.png
    - assets/page-1/images/vector-jHz.png
    - assets/page-1/images/vector-HV2.png
    - assets/page-1/images/icon-bell-circle-fill-xzt.png
    - assets/Paypal_logo.png
    - assets/MoMo_Logo.png
    - assets/qr_momo.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
